on: [push]

name: build docker image for bsc node

jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - run: echo "IMAGE_TAG=$(echo "$GITHUB_REF" | sed 's/refs\/tags\///g' | sed 's/\//-/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: docker-cache
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        id: contracts_docker_build
        with:
          push: true
          cache-from: type=local,src=/tmp/.docker-cache
          cache-to: type=local,dest=/tmp/.docker-cache
          tags: forestfriends/bsc:${{env.IMAGE_TAG}}
      - run: echo ${{ steps.contracts_docker_build.outputs.digest }}
