on: [push]

name: build docker image for bsc node

jobs:
  docker:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - run: echo "IMAGE_TAG=$(echo "$GITHUB_REF" | sed 's/refs\/heads\///g' | sed 's/\//-/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: bsc
          image-tag: ${{env.IMAGE_TAG}}
          custom-args: --build-arg VERSION=${{env.IMAGE_TAG}}
